version: "3.8"

services:
  web-extractor:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: web-content-extractor
    ports:
      - "8000:8000"
    volumes:
      - ../output:/app/output
    environment:
      - LOG_LEVEL=INFO
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
    command: "https://example.com --format json --output-file"
    depends_on:
      - azurite

  # Azure Storage Emulator
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000" # Blob
      - "10001:10001" # Queue
      - "10002:10002" # Table
    volumes:
      - ../azurite-data:/data
    command: "azurite --silent --location /data --debug /data/debug.log --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
