extraction:
  request_timeout: 30
  max_retry_attempts: 3
  user_agent: "WebContentExtractor/1.0"
  enable_link_validation: true

output:
  default_format: "json"
  output_directory: "./output"
  include_metadata: true
  timestamp_files: true
